-- Schemas used for the PostgreSQL database
-- includes information about specific design decisions

CREATE TABLE IF NOT EXISTS Artist (
	artist_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	artist_name TEXT NOT NULL,
	artist_type TEXT NOT NULL,
	artist_country TEXT NOT NULL,
	artist_disambiguation TEXT, -- additional info to distinguish artists with similar names
	is_disbanded BOOL DEFAULT FALSE,
	created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
)

CREATE TABLE IF NOT EXISTS Albums (
	album_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	album_name TEXT NOT NULL,
	num_of_songs SMALLINT NOT NULL CHECK (num_of_songs >= 0),
	date_released DATE NOT NULL,
	album_type TEXT, -- e.g. album, ep, single
	created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
	artist_id INTEGER REFERENCES artists(artist_id)
)

CREATE TABLE IF NOT EXISTS Songs (
	song_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	song_name TEXT NOT NULL,
	song_length INTEGER,
	date_released DATE NOT NULL,
	track_number SMALLINT, -- smallint due to typical album length
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
	album_id INTEGER REFERENCES albums(album_id)
)

-- Associative table to allow songs to have multiple artists
CREATE TABLE IF NOT EXISTS Song_Artists (
	song_id INTEGER NOT NULL REFERENCES songs(song_id) ON DELETE CASCADE,
	artist_id INTEGER NOT NULL REFERENCES artists(artist_id) ON DELETE CASCADE, -- deletes association if either song/artist are deleted
	PRIMARY KEY (song_id, artist_id)	
)



-- Create trigger to update 'updated_at' timestamp on record modification
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
	NEW.updated_at = now();
	RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Attach trigger to all tables with updated_at field
CREATE TRIGGER artists_set_updated_at
BEFORE UPDATE ON artists
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER albums_set_updated_at
BEFORE UPDATE ON albums
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER songs_set_updated_at
BEFORE UPDATE ON songs
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

--  TO DO: add trigger to userartistprefs, artistnotes, users, artistnotes, usersongprefs, playlists tables